#image: mcr.microsoft.com/dotnet/sdk:latest

#before_script:
#  - 'dotnet restore'

build_1:
  stage: build
  script:
  - 'dotnet build --no-restore'

test_qwe:
  stage: test
  script:
  - 'dotnet test'